---

- name: Create HAproxy directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ haproxy_config_directory }}"

- name: Set Docker container parameters
  set_fact:
    haproxy_container_parameters:
      name: "{{ haproxy_name }}"
      image: "{{ haproxy_image }}"
      state: started
      published_ports: "{{ haproxy_ports }}"
      volumes:
        - "{{ haproxy_config_directory }}:/usr/local/etc/haproxy:ro"

- name: Template HAProxy config
  template:
    src: "{{ haproxy_config_template }}"
    dest: "{{ haproxy_config_directory }}/haproxy.cfg"
  notify: Reload HAProxy

- name: Create HAproxy container
  docker_container: "{{ haproxy_container_parameters | combine(haproxy_docker_additional_options) }}"
  register: haproxy_container

- name: Create haproxy-reload command
  template:
    src: haproxy-reload.j2
    dest: /usr/local/bin/haproxy-reload
    mode: '0755'

- name: Create haproxy-restart command
  template:
    src: haproxy-restart.j2
    dest: /usr/local/bin/haproxy-restart
    mode: '0755'

- name: Create haproxy-edit command
  template:
    src: haproxy-edit.j2
    dest: /usr/local/bin/haproxy-edit
    mode: '0755'
